#!/usr/bin/env bash

#Shortcuts of colors
RED='\e[31m'
GREEN='\e[32m'
YELLOW='\e[33m'
BLUE='\e[34m'
RESET='\e[0m'

OK="${GREEN}[OK]${RESET}"
ERROR="${RED}[ERROR]${RESET}"

SSHPORT="10122" #Default new value of OpenSSH port
#Parsing cycle
while [[ $# -gt 0 ]]; do
    case "$1" in
        --port)
            SSHPORT="$2"
            shift 2
            ;;
        *)
            echo -e "An unknown parameter was passed: $1"
            echo -e "$ERROR installation was cancelled"
            exit 1
            ;;
    esac
done

#Check if personal ssh-key avaliable on vm, else exit script
if [[ ! -s /root/.ssh/authorized_keys ]]; then
    echo -e "${RED}No SSH key found for root. Aborting....${RESET}"
    exit 1
fi

#Update and upgrade new system
sudo apt update -y
sudo apt upgrade -y

#TO THINK
#apt-get -y \
#    -o Dpkg::Options::="--force-confdef" \
#    -o Dpkg::Options::="--force-confold" \
#    dist-upgrade

#Check if UFW is install on VM
if ! command -v ufw >/dev/null 2>&1; then
    sudo apt install -y ufw
fi

#Refresh screen after updates
clear

echo -e "$OK System was sucsessfully updated"

#Change default OpenSSH port to custom 10122 port-ssh
sed -i "s|^#\?Port .*$|Port ${SSHPORT}|" "/etc/ssh/sshd_config"

#Reload daemon to activate new SSH port
sudo systemctl daemon-reload && sudo systemctl restart ssh

#Show current listening ports
echo -e "$OK Default OpenSSH port was changed to $SSHPORT"

#Disable password authentification
sed -i "s|^#\?PasswordAuthentication .*$|PasswordAuthentication no|" \
    /etc/ssh/sshd_config

#Check if the file even exist
if [[ -f /etc/ssh/sshd_config.d/50-cloud-init.conf ]]; then
    sed -i "s|^#\?PasswordAuthentication .*$|PasswordAuthentication no|" \
        /etc/ssh/sshd_config.d/50-cloud-init.conf
fi

#restart systemclt daemon to apply changes
if sshd -t; then
    systemctl restart ssh
else
    echo -e "${RED}SSH config contains errors${RESET}"
    exit 1
fi

echo -e "$OK SSH-password authentification was disabled"


UFW_RULES_FILE="/etc/ufw/before.rules"

#Reset ufw setting before setting up
sudo ufw --force reset > /dev/null 2>&1

# Change ACCEPT to DROP in icmp code for INPUT
sed -i 's/-A ufw-before-input -p icmp --icmp-type destination-unreachable -j ACCEPT/-A ufw-before-input -p icmp --icmp-type destination-unreachable -j DROP/' "$UFW_RULES_FILE"
sed -i 's/-A ufw-before-input -p icmp --icmp-type time-exceeded -j ACCEPT/-A ufw-before-input -p icmp --icmp-type time-exceeded -j DROP/' "$UFW_RULES_FILE"
sed -i 's/-A ufw-before-input -p icmp --icmp-type parameter-problem -j ACCEPT/-A ufw-before-input -p icmp --icmp-type parameter-problem -j DROP/' "$UFW_RULES_FILE"
sed -i 's/-A ufw-before-input -p icmp --icmp-type echo-request -j ACCEPT/-A ufw-before-input -p icmp --icmp-type echo-request -j DROP/' "$UFW_RULES_FILE"

#Append a new string to rules
sed -i '/-A ufw-before-input -p icmp --icmp-type echo-request -j DROP/a -A ufw-before-input -p icmp --icmp-type source-quench -j DROP' "$UFW_RULES_FILE"

# Change ACCEPT to DROP in icmp code for FORWARD
sed -i 's/-A ufw-before-forward -p icmp --icmp-type destination-unreachable -j ACCEPT/-A ufw-before-forward -p icmp --icmp-type destination-unreachable -j DROP/' "$UFW_RULES_FILE"
sed -i 's/-A ufw-before-forward -p icmp --icmp-type time-exceeded -j ACCEPT/-A ufw-before-forward -p icmp --icmp-type time-exceeded -j DROP/' "$UFW_RULES_FILE"
sed -i 's/-A ufw-before-forward -p icmp --icmp-type parameter-problem -j ACCEPT/-A ufw-before-forward -p icmp --icmp-type parameter-problem -j DROP/' "$UFW_RULES_FILE"
sed -i 's/-A ufw-before-forward -p icmp --icmp-type echo-request -j ACCEPT/-A ufw-before-forward -p icmp --icmp-type echo-request -j DROP/' "$UFW_RULES_FILE"

echo -e "$OK Server ping was disabled"

#Setting up an ufw
sudo ufw default deny incoming > /dev/null 2>&1
sudo ufw default allow outgoing > /dev/null 2>&1

sudo ufw allow 80/tcp > /dev/null 2>&1
sudo ufw allow 443/tcp > /dev/null 2>&1
sudo ufw allow 443/udp > /dev/null 2>&1
sudo ufw allow $SSHPORT/tcp > /dev/null 2>&1

sudo ufw --force enable > /dev/null 2>&1

echo -e "$OK Firewall was configured and enabled\n"





